### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by pabbo** [benhuson/password-protected#103]
Everything has been working really good until today. Logged in multiple times today, didn't change the password went to go log back in hours later and now it's saying incorrect password. 

Cannot access wp-admin.php to disable it or change the password now.

**Comment by bboerendans** [comment]
same issue overhere

**Comment by pabbo** [comment]
Thank you


Thank you,

Patrick Abbo
President, Syndora Dynamics
*P: *(800) 978-4963 | *M: *(248) 971-8148 | www.syndora.com |
PO Box 82026, Rochester, MI 48308

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.
