### ISSUE TITLE
Update 2.2 is breaking wordpress

### ISSUE THREAD

**Issue by jismonthomas1** [benhuson/password-protected#104]
Just ran the new update, it is breaking the whole website to some errors

**Comment by benhuson** [comment]
Please could you provide further information:

- What version of WordPress are you using?
- What is breaking? Is it showing errors or are you just getting a white screen?

**Comment by ratty75** [comment]
Same issue here, blank white screen when the plugin is activated. Using WordPress v4.9.6. Any chance we can downgrade until this is fixed?

**Comment by jismonthomas** [comment]
I am using the latest version 4.9.6, for me it wasn't blank page, instead it was showing bunch of php errors, then had to revert back to the previous version.

@ratty75 you can find the previous versions here : https://wordpress.org/plugins/password-protected/advanced/
scroll to the very bottom

**Comment by paulmil** [comment]
I  used a plugin called rollback and was able to rollback to version 2.1

**Comment by benhuson** [comment]
@jismonthomas Are you able to post the PHP error you had to help me diagnose the issue, thanks.

**Comment by benhuson** [comment]
Please try the development version which hopefully includes a fix for the PHP error which may resolve the other issues. You can download it here:

https://github.com/benhuson/password-protected/archive/develop.zip

If anyone can confirm if this fixes their issue that would be super helpful.

Thanks

**Comment by jismonthomas** [comment]
@benhuson sorry, I couldn’t take a detailed look at the error at that time since I already shared my site with the client, but it was something like timeout around line 240 I believe.

**Comment by benhuson** [comment]
No worries, I have tracked down a PHP error which is fixed in the develop version above. If you are able to download that version and try it that would be most appreciated. Hopefully it will fix your issue 🤞🏻

**Comment by benhuson** [comment]
This should now be fixed in version [2.2.1](https://github.com/benhuson/password-protected/releases/tag/2.2.1)

Please open a new issue if you are still having problems.
