### ISSUE TITLE
2.2 update - password protects every page

### ISSUE THREAD

**Issue by beantree74** [benhuson/password-protected#105]
After update the plugin page requires me to enter password for every page I visit throughout site. Any solution to only have password login for just entering site?

**Comment by benhuson** [comment]
Please try the development version which hopefully includes a fix for the PHP error which may resolve the other issues. You can download it here:

https://github.com/benhuson/password-protected/archive/develop.zip

If you can confirm if this fixes your issue that would be super helpful.

Thanks

**Comment by beantree74** [comment]
Problem solved! Thank you!

**Comment by benhuson** [comment]
Thank you for testing. If wil push out a new version with the fix later today.

**Comment by benhuson** [comment]
This should now be fixed in version [2.2.1](https://github.com/benhuson/password-protected/releases/tag/2.2.1)
