### ISSUE TITLE
2.2 not working

### ISSUE THREAD

**Issue by paulmil** [benhuson/password-protected#106]
Hi Version 2.2 is not working all the time. When it does it askes for a password everytime you click on another page
WordPress 4.9.6

**Comment by benhuson** [comment]
Please try the development version which hopefully includes a fix for the PHP error which may resolve the other issues. You can download it here:

https://github.com/benhuson/password-protected/archive/develop.zip

If you can confirm if this fixes your issue that would be super helpful.

Thanks

**Comment by megancoleman** [comment]
The latest version had stopped working for me too (the password just wouldn't work, it would just keep reloading the protected login), and the development version totally fixed the issue. Thanks!

**Comment by benhuson** [comment]
Thank you for testing.

I’ll push out the fix in a release later today.

**Comment by benhuson** [comment]
This should now be fixed in version [2.2.1](https://github.com/benhuson/password-protected/releases/tag/2.2.1)
