### ISSUE TITLE
Breaks REST API for non logged-in users

### ISSUE THREAD

**Issue by thykka** [benhuson/password-protected#113]
While Password Protected is activated, only logged-in users can send forms via CF7.
This happens even if Password Protected status is not enabled in the plugin's options.

Attempting to submit a CF7 form results in a call to this endpoint

example.com/wp-json/contact-form-7/v1/contact-forms/```form-id```/feedback

results in a 401 error and the following payload:

```{"code":"rest_cannot_access","message":"Only authenticated users can access the REST API.","data":{"status":401}}```

Deactivating Password Protected allows the form to be submitted again.

**Comment by benhuson** [comment]
Thank you for the pull request. I will ensure this fix is in the next release.

**Comment by benhuson** [comment]
Hopefully fixed in version 2.2.3
