### ISSUE TITLE
Resetting Password

### ISSUE THREAD

**Issue by bambamdan** [benhuson/password-protected#132]
The password I created with Password Protected is no longer working.

Is it possible to reset the password? Or, is it possible to locate what the password is somewhere?
 
Thanks!

**Comment by benhuson** [comment]
If you can still login to your admin, you can edit it on the settings page, otherwise you need to disable/remove the plugin to log back in.

You cannot locate the password as it is encrypted when stores so you would need to set a new one.

**Comment by bambamdan** [comment]
This is what I did to get in. Thank you for the prompt reply.

Danny Waddell
Principal, The Bam Bam Agency
808.757.5940

**Comment by mycanaletto** [comment]
I need to delete the password on a very old site. I only have ssh access, is there a procedure?

Thank you for your help!
