### ISSUE TITLE
Is it possible for the cookie name to be configurable?

### ISSUE THREAD

**Issue by carl-alberto** [benhuson/password-protected#140]
Would it be possible if the cookie name to be configurable so it can be renamed for hosts that has specific naming conventions to work well with caching eg. Pantheon https://pantheon.io/docs/cookies/#cache-busting-cookies?

Or maybe at least have a prefix wp-bid_1_password_protected_auth or wordpress-bid_1_password_protected_auth like most of the popular plugins?

**Comment by jocastaneda** [comment]
Howdy!

I just wanted to pass this along and would love to get your feedback on this Ben. I made a quick adjustment here: https://github.com/jocastaneda/password-protected/blob/cookie-name-filter/password-protected.php#L649

I can happily submit a PR too if that works better that would address this so potentially others might see some use out of this.

**Comment by benhuson** [comment]
@jocastaneda If you could submit a PR that would be great - thank you :)

**Comment by jocastaneda** [comment]
Done! :D
