### ISSUE TITLE
Warnings of password-protected page in w3 validator

### ISSUE THREAD

**Issue by dianamurcia** [benhuson/password-protected#161]
In order to make the password-protected page passed in https://validator.w3.org/:

<img width="735" alt="Screenshot 2020-05-08 at 15 44 03" src="https://user-images.githubusercontent.com/1894664/81411516-c360ee00-9142-11ea-920b-a7f3338df218.png">

Remove attribute `type="text/javascript"` from `<script>` tags.
Remove attribute `type="text/css"` from `<style>` tags.

from the **/plugins/password-protected/theme/password-protected-login.php** file.

I'd love to send a pull request, but it seems I have mistaken the branches, sorry @benhuson 😊

**Comment by benhuson** [comment]
Thanks. Fix in:
