### ISSUE TITLE
Plugin will not work

### ISSUE THREAD

**Issue by nick907** [benhuson/password-protected#164]
I have 8 sites using this plugin. All same hosting plan. No caching plugins. The plugin works on 6 sites. The last 2 sites are the newest. I took one site and deactivated every plugin and re-installed wordpress and it will still not work. Password protected is the only active plugin. All sites using latest wordpress V 5.4.1

By not work I mean you visit the site, the plugin is active and asks for the password. You type in the password, browser spins for a bit and then the page is just refreshed asking for the password again.

I tried long passwords and short. Current password is 1234. Cant gain access.

If I switch to the "Hide my site" plugin it works fine it just doesn't look as nice or integrate with login logo.

What can I try at this point? Why is it working on the other sites and not these?

**Comment by nick907** [comment]
From my host: According to our check, the cookie file is not being generated

**Comment by benhuson** [comment]
Hi Nick,

Please download this version of the plugin to which I have added a debugging feature:
https://github.com/benhuson/password-protected/archive/feature/debugging.zip

Install that and:

1. Go to the Password Protected Settings and check the "Enable Debugging" checkbox.
2. Go to the frontend and recreate the issue with the password not working.
3. Go back to the Password Protected Settings page and at the bottom there should be a log of what happened.
4. Copy the log and email it to me so I can see if its gives any clues.

Disabling the "Enable Debugging" checkbox will clear the log.
Just keep if on while testing it - don't leave it on as it will keep generating a long log!

Thanks

**Comment by benhuson** [comment]
The issue may also be fixed by the change #166 if you would like to try it.

**Comment by benhuson** [comment]
Just found another older issue where a user found that NameCheap didn't like the test cookie that is set.  Please see link below how you can edit the `password-protected-login.php` file in the plugin to see if this helps with your issue.

https://wordpress.org/support/topic/password-protected-plug-in-408-request-time-out/

**Comment by nick907** [comment]
Hi Ben,

Thanks fro doing that. Here is the log and also a snapshot

-----
Start validating cookie.
Auth cookie malformed.
-----
Start validating cookie.
Auth cookie malformed.
-----
Start validating cookie.
Auth cookie malformed.

[image: image.png]

**Comment by nick907** [comment]
This namecheap solution below worked!! Debugging log was empty.

file location: wp-content/plugins/password-protected/theme/password-protected-login.php
line number: 115
change this: <input type=”hidden” name=”testcookie” value=”1″ />
to this: <input type=”hidden” name=”testcookie_fix” value=”1″ /> 

For me it was line 132

The only baffling thing left is how the 6 other sites on the same namecheap plan work. I think the reason is related to their origin. The 6 working sites were built a while ago at Go Daddy and migrated to Namecheap. The 2 sites that werent working were new and built on Namecheap.

Either way thanks for your help in solving this.

**Comment by benhuson** [comment]
Great, I’ll make sure the fix is included in the next release!

Thank you for helping to test

Ben

**Comment by benhuson** [comment]
Hi @nick907 

Just one more test if you could....?

In the `wp-content/plugins/password-protected/theme/password-protected-login.php` file, where you changed the value of "testcookie" to "testcookie_fix" around line 132, please could you try changing it to "password_protected_cookie_test".

Then also in the same file around line 52 there is another instance of "testcookie" - please could you also change that to "password_protected_cookie_test".

The test in line 52 should check if your browser supports cookies OK, and just changing the one instance of "testcookie" further down in the page breaks this check. I'm keen to see if it is the cookie test that is broken, or whether it is just the name "testcookie" that is causing an issue.

Thanks

Ben

**Comment by benhuson** [comment]
I have found support threads for other plugin expanding on the Namecheap cookie issue. It would seem they block all requests that contain a "testcookie" POST parameter, so changing to anything else should work. Will be change to "password_protected_cookie_test" in the next release of the plugin.
