### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by klokie** [benhuson/password-protected#46]
Hi, thanks for your plugin – it's very useful!
I'd like to make a change – altering the login URL path to /login/ from a query string parameter – but I'm not sure what the most recent version I should use.

The version active on the site I'm working with is 1.9 from https://wordpress.org/plugins/password-protected/ but this GitHub repo has 1.8 as the latest tagged version. Would you mind updating either the repo or the documentation and tag? thanks

**Comment by benhuson** [comment]
Hi Daniel,

Sorry, well spotted.

I've updated the latest tagged version on GitHub.

Please submit any changes and pull requests to the 'master' branch on GitHub

Kind regards

Ben

**Comment by klokie** [comment]
That's great, thanks.
