### ISSUE TITLE
Add hint?

### ISSUE THREAD

**Issue by MusikDK** [benhuson/password-protected#48]
Is it possible to add a hint to the login-page? Like if some people only once in a while will visit the page, it would be nice to show a hint

**Comment by benhuson** [comment]
You can use the `password_protected_login_messages` or `password_protected_before_login_form` hooks to output a message or content on the login form.

Or you can install this plugin which adds fields into the settings panel in the admin so you can add content there: https://github.com/benhuson/password-protected-customizer
