### ISSUE TITLE
When sharing to facebook, I get a link to the password protected site even though it's no longer password protected.

### ISSUE THREAD

**Issue by beatelite** [benhuson/password-protected#75]
**Summary:**
When disabling a password protection via the plugin and sharing the site url via facebook, It leads users to the password_protected url version of the site. 

**Repro steps:**
Enable password protection on a site
disable it
share the url to site only  on facebook (without the password protection url part)

**Current results:**
the password protection url is shared instead of the regular url. 

**Expected results:**
For the regular url to show up and link people to the non-password protected site.

**Comment by BandonRandon** [comment]
Hi @beatelite just came across this, Facebook does Cache URLs did you run the site through their [Debug Tool](https://developers.facebook.com/tools/debug/) after disabling the plugin? If not give that a try.

**Comment by benhuson** [comment]
The Facebook debug tool mentioned above should work. Thanks @BandonRandon
