### ISSUE TITLE
Hi Ben - Help please!

### ISSUE THREAD

**Issue by Edc2** [benhuson/password-protected#81]
Hi Ben,

I have a big problem in that i forgot my password and can't access the website as the owner/administrator.

Is it simply possible to delete the password protected folder in my C panel? If so, I would then be able to reload a new version of password protected onto my website. 

I'm not a programer so this might be to simple of a solution.

Your help is greatly appreciated.

Ed

**Comment by benhuson** [comment]
Hi Ed,

If you are able to delete the password protected plugin folder it will
remove the password protection.

You should still be able to access the WordPress admin login screen to
recover you user login details though?

Ben

**Comment by Edc2** [comment]
Thanks for the help Ben.
Ed
