### ISSUE TITLE
Feature Request: Indication on admin that WPP is active

### ISSUE THREAD

**Issue by espirit** [benhuson/password-protected#85]
It would be nice to have an indication (changed admin them color?) when password protect is active.

This will help, not to forget to re-enable the site. Specially useful if you have your own IP address whitelisted.

Maybe an indication on the front-end side (when running in a different or anonimous browser) can be added.

**Comment by benhuson** [comment]
Have added a padlock icon to the menu bar when logged into the admin.

It is highlight red when password protection is active.

https://github.com/benhuson/password-protected/commit/2e65b5b9524ce2c52d42a62c16052af75376e390

Will be in the next main plugin release.
