### ISSUE TITLE
mobile view not working?

### ISSUE THREAD

**Issue by skynet2809** [benhuson/password-protected#99]
Plugin works very well.

Just it will not display correctly on any mobile phone, while the rest of my site does.

Any help or updates?

PS: Thanks for the great work.

**Comment by BeltSen** [comment]
I just figured as well that it really does not work.

If you add the following to line 58 (basically after <head> but before <title> with the other <meta> elements) in password-protected/theme/password-protected-login.php and reupload the file it works.

<meta name="viewport" content="width=device-width, initial-scale=1.0">

@benhuson First of all: Thank you very much for your plugin! Your work is hugely appreciated! Thank you, thank you! - Regarding this topic, I don't really understand why it is not included in the plugin by default? Maybe, it deserves to be added?

**Comment by jwettig** [comment]
@BeltSen What did you add to the file? It seems you forgot to include it into your comment. I have the same problem as well right now and

**Comment by BeltSen** [comment]
It's `<meta name="viewport" content="width=device-width, initial-scale=1.0">`. In my previous message, I didn't format the pasted code as `code` which, apparently prevented it from being displayed. I fixed it. Good luck! ;)

**Comment by jwettig** [comment]
@BeltSen Awesome! Thanks a lot :)

**Comment by kartik-pawar** [comment]
@BeltSen thank you so much, i was stuck trying to find the solution for so long

**Comment by BeltSen** [comment]
@kartik-pawar You are very welcome. I am glad it helps other people =) Happy New Year! :)
